# DB
spring:
  datasource:
    profiles:
      include: prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carrotMarket?serverTimezone=UTC&characterEncoding=UTF-8
    username: carrot
    password: 1234
  config:
    use-legacy-processing: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      jdbc:
        time_zone: Asia/Seoul
      dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate:
        show_sql: true
        format_sql: true

# Logging level
logging:
  level:
    com:
      example:
        carrotmarket: debug