spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://umc-4th-pratice.cckac2d5rtqn.ap-northeast-2.rds.amazonaws.com:3306/carrotMarket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: sju093475

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true