logging:
  level:
    com.example.carrotmarket: debug
    org.hibernate.SQL: debug

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
---
# Settings for local
spring:
  config.activate.on-profile: local
  datasource:
    url: ${CARROT_MARKET_LOCAL_DB_URL}
    username: ${CARROT_MARKET_LOCAL_DB_USERNAME}
    password: ${CARROT_MARKET_LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
---
spring:
  config.activate.on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://umc-4th-pratice.cckac2d5rtqn.ap-northeast-2.rds.amazonaws.com:3306/carrotMarket?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: sju093475

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true